services:
  ark:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SESSION_NAME: ${SESSION_NAME}
        SERVER_MAP: ${SERVER_MAP}
        SERVER_PASSWORD: ${SERVER_PASSWORD}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        MAX_PLAYERS: 2
        UPDATE_ON_START: true
        BACKUP_ON_STOP: true
        PRE_UPDATE_BACKUP: true
        WARN_ON_STOP: true
        ENABLE_CROSSPLAY: false
        DISABLE_BATTLEYE: true
        ARK_SERVER_VOLUME: /srv/ark
        GAME_CLIENT_PORT: 7777
        UDP_SOCKET_PORT: 7778
        RCON_PORT: 27020
        SERVER_LIST_PORT: 27015
        GAME_MOD_IDS:
    container_name: ark
    hostname: ark
    restart: unless-stopped
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
      - 7778:7778/tcp
      - 7778:7778/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27020:27020/tcp
      - 27020:27020/udp
    volumes:
      - ./data:/srv/ark:rw
    environment:
      SESSION_NAME: ${SESSION_NAME}                                             # The name of your ARK-session which is visible in game when searching for servers
      SERVER_MAP: ${SERVER_MAP}                                                 # Desired map you want to play
      SERVER_PASSWORD: ${SERVER_PASSWORD}                                       # Server password which is required to join your session. (overwrite with empty string if you want to disable password authentication)
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}                                         # Admin-password in order to access the admin console of ARK
      MAX_PLAYERS: 2                                                            # Maximum number of players to join your session
      UPDATE_ON_START: true                                                     # Whether you want to update the ARK-server upon startup or not
      BACKUP_ON_STOP: true                                                      # Create a backup before gracefully stopping the ARK-server
      PRE_UPDATE_BACKUP: true                                                   # Create a backup before updating ARK-server
      WARN_ON_STOP: true                                                        # Broadcast a warning upon graceful shutdown
      ENABLE_CROSSPLAY: false                                                   # Enable crossplay. When enabled battleye should be disabled as it likes to disconnect epic players
      DISABLE_BATTLEYE: true                                                    # Disable Battleye protection
      ARK_SERVER_VOLUME: /srv/ark                                               # Path where the server-files are stored
      GAME_CLIENT_PORT: 7777                                                    # Exposed game-client port
      UDP_SOCKET_PORT: 7778                                                     # Raw UDP socket port (always Game client port +1)
      RCON_PORT: 27020                                                          # Exposed RCON port
      SERVER_LIST_PORT: 27015                                                   # Exposed server-list port
      GAME_MOD_IDS:                                                             # Additional game-mods you want to install, seperated by comma. (e.g. GAME_MOD_IDS=487516323,487516324,487516325)
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"
        max-size: 1m
        max-file: 5
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          cpus: '0.2'
          memory: 8G